/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ext_NoradLink */

#ifndef _Included_ext_NoradLink
#define _Included_ext_NoradLink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ext_NoradLink
 * Method:    getSatHorizonCoordinates
 * Signature: (Lobservation/interference/Satellite;JLobservation/Telescope;)Lastrometrics/HorizonCoordinates;
 */
JNIEXPORT jobject JNICALL Java_ext_NoradLink_getSatHorizonCoordinates
  (JNIEnv *, jobject, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
